# yaml-language-server: $schema=https://raw.githubusercontent.com/ebi-metagenomics/nf-modules/master/subworkflows/yaml-schema.json
name: "combined_gene_caller"
description: |
  MGnify combined gene calling.
  This workflow runs gene prediction with Pyrodigal and FragGeneScanRS, and then combines the resulting predictions.
  The merged output contains all the gene predictions from Pyrodigal, along with genes predicted by FragGeneScanRS
  that do not overlap with any Pyrodigal gene.
  Optionally, it can mask (remove) genes that overlap with regions from a masking file.
keywords:
  - gene finding
  - gene prediction
  - prokaryotes
  - microbial

components:
  - pyrodigal:
      git_remote: https://github.com/nf-core/modules.git
  - fraggenescanrs
  - combinedgenecaller/merge

input:
  - ch_assembly:
      type: map
      description: |
        An input channel containing the following files:
        - assembly: One or more assembly or genome contigs fasta file.
        Structure: [ meta, assembly ]
  - ch_mask_file:
      type: map
      description: |
        An input channel containing the following files:
        - mask: One or more tblout files generated by Infernal cmscan or cmsearch.
        Structure: [ meta, mask_file ]

output:
  - faa:
      type: file
      description: protein translations of the predicted genes
      pattern: "*.faa"
  - ffn:
      type: file
      description: nucleotide sequences of the predicted genes
      pattern: "*.ffn"
  - gff:
      type: file
      description: gene annotations in gff format
      pattern: "*.gff"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
authors:
  - "@mberacochea"
