# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pimento_generatebcv"
description: Generate Base-Conservation Vectors (BCV) in a stepwise and windowed manner for a fastq file.
keywords:
  - primers
  - sequencing
  - genomics
  - metagenomics
tools:
  - "pimento":
      description: "A PrIMEr infereNce TOolkit to facilitate large-scale calling of metabarcoding amplicon sequence variants"
      homepage: "https://github.com/EBI-Metagenomics/PIMENTO"
      documentation: "https://github.com/EBI-Metagenomics/PIMENTO"
      tool_dev_url: "https://github.com/EBI-Metagenomics/PIMENTO"
      licence: ["Apache-2.0"]
      identifier: biotools:PIMENTo

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - fwd_flag:
        type: string
        description: String that controls whether the forward strand of a merged fastq
          file | should have its MCP proportions assessed. If it should, | string value
          should be "auto"
        pattern: "{auto,none}"
    - rev_flag:
        type: string
        description: String that controls whether the reverse strand of a merged fastq
          file | should have its MCP proportions assessed. If it should, | string value
          should be "auto"
        pattern: "{auto,none}"
    - fastq:
        type: file
        description: Merged or single-end FASTQ file
        pattern: "*.fastq.gz"

output:
  - tsv:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*.tsv":
          type: file
          description: .tsv file containing MCP proportion results for all given strands
          pattern: "*.tsv"
  - versions:
      - "versions.yml":
          type: file
          description: File containing software versions
          pattern: "versions.yml"

authors:
  - "@chrisata"
maintainers:
  - "@chrisata"
