# yaml-language-server: $schema=https://raw.githubusercontent.com/ebi-metagenomics/nf-modules/master/subworkflows/yaml-schema.json
name: "amr_annotation"
description: AMR annotation, harmonisation and integration
keywords:
  - amr
  - deeparg
  - rgi
  - amrfinderplus
  - hamronization
  - gff
components:
  - deeparg/downloaddata:
      git_remote: https://github.com/nf-core/modules.git
  - deeparg/predict:
      git_remote: https://github.com/nf-core/modules.git
  - hamronization/deeparg:
      git_remote: https://github.com/nf-core/modules.git
  - rgi/cardannotation:
      git_remote: https://github.com/nf-core/modules.git
  - rgi/main:
      git_remote: https://github.com/nf-core/modules.git
  - hamronization/rgi:
      git_remote: https://github.com/nf-core/modules.git
  - amrfinderplus/update:
      git_remote: https://github.com/nf-core/modules.git
  - amrfinderplus/run:
      git_remote: https://github.com/nf-core/modules.git
  - hamronization/amrfinderplus:
      git_remote: https://github.com/nf-core/modules.git
  - untar:
      git_remote: https://github.com/nf-core/modules.git
  - amr_integrator
input:
  - ch_inputs:
      type: tuple
      description: |
        The input channel containing the genes, proteins and gff files
        Structure: [ val(meta), path(genes), path(proteins), path(cds_gff) ]
  - ch_deeparg_inputs:
      type: file
      description: |
        The input channel containing the database for deeparg and versions
        Structure: [ path(deeparg_model), val(deeparg_version), val(deeparg_db_version) ]
  - ch_rgi_inputs:
      type: file
      description: |
        The input channel containing the path to the RGI databases
        Structure: [ path(card_db), path(wildcard_db) ]
  - ch_amrfinderplus_db:
      type: file
      description: |
        The input channel for the compressed tarball of the AMRFinderPlus database to query
        Structure: [ path(amrfinderplus_db) ]
output:
  - gff:
      type: file
      description: |
        Channel containing a GFF3 file
        Structure: [ val(meta), path(gff) ]
      pattern: "*.gff"
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
authors:
  - "@Ales-ibt"
