# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "pathofact2_virulence"
description: Pathofact2 - Machine Learning tool to predict virulence factors in protein sequences
keywords:
  - prediction
  - virulence
  - pathofact2
tools:
  - "pathofact2":
      description: "PathoFact 2.0, an enhanced pipeline for improved ARG, VF, and toxin prediction in prokaryotic protein sequences"
      homepage: "https://gitlab.lcsb.uni.lu/ESB/PathoFact2"
      documentation: "https://gitlab.lcsb.uni.lu/ESB/PathoFact2"
      tool_dev_url: "https://gitlab.lcsb.uni.lu/ESB/PathoFact2"
      doi: "10.1101/2024.12.09.627531"
      licence: ["GNU v3.0"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - fasta:
        type: file
        description: Protein sequences in FASTA format
        pattern: "*{fasta,fasta.gz,fa,fa.gz,fna,fna.gz,faa,faa.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1929" # FASTA
  - zenodo_file:
      type: file
      description: Pathofact2 databases downloaded from zenodo. The tarball contains the Models db
output:
  tsv:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*_classifier_virulence.tsv":
          type: file
          description: Predicted virulence factors tsv file
          pattern: "*.tsv"
          ontologies:
            - edam: "http://edamontology.org/format_3475" # TSV
  versions_python:
    - - "${task.process}":
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - "python --version | sed 's/Python //g'":
          type: string
          description: Command used to obtain the tool version

authors:
  - "@Ales-ibt"
maintainers:
  - "@Ales-ibt"
