repos:
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: "v4.0.0-alpha.8"
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.2.5
  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.31.0
    hooks:
      - id: check-jsonschema
        # match meta.ymls in one of the subdirectories of modules/ebi-metagenomics
        files: ^modules/ebi-metagenomics/.*/meta\.yml$
        args: ["--schemafile", "modules/yaml-schema.json"]
      - id: check-jsonschema
        # match meta.ymls in one of the subdirectories of subworkflows/ebi-metagenomics
        files: ^subworkflows/ebi-metagenomics/.*/meta\.yml$
        args: ["--schemafile", "subworkflows/yaml-schema.json"]
      - id: check-github-workflows
  - repo: https://github.com/renovatebot/pre-commit-hooks
    rev: 39.138.2
    hooks:
      - id: renovate-config-validator
  # use ruff for python files
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.3
    hooks:
      - id: ruff
        files: \.py$
        args: [--fix, --exit-non-zero-on-fix, "--select", "I,E1,E4,E7,E9,F,UP,N"] # sort imports and fix (rules taken from nf-core/tools)
      - id: ruff-format # formatter
