name: "dram_distill"
description: Produces summary files with DRAM distill
keywords:
  - annotation
  - visualisation
  - dram
tools:
  - "DRAM":
      description: "Summarises annotations from multiple tools like KEGG, Pfam and CAZy."
      args_id: "$args"
      homepage: "https://github.com/WrightonLabCSU/DRAM"
      documentation: "https://github.com/WrightonLabCSU/DRAM/wiki"
      doi: "10.1093/nar/gkaa621"
      licence: ["GPL v3"]
      identifier: biotools:dram

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - tsv_input:
        type: file
        description: "Input tsv file containing sequence annotations from different tools"
        pattern: "*.tsv"
  - - dram_dbs:
        type: directory
        description: "The DRAM reference databases folder"
output:
  - html:
      - meta:
          type: file
          description: "The meta map"
          pattern: "*.html"
      - "*_dram.html.gz":
          type: file
          description: "HTML file containing heatmaps of summarised annotations"
          pattern: "*.html"
  - out_tsv:
      - meta:
          type: map
          description: "The meta map"
      - "*_dram.tsv.gz":
          type: file
          description: "TSV file containing summarised annotations"
  - stats_tsv:
      - meta:
          type: map
          description: "The meta map"
      - "*_genome_stats.tsv.gz":
          type: file
          description: "TSV file the stats per genome"
  - metabolism_xslx:
      - meta:
          type: map
          description: "The meta map"
      - "*_metabolism_summary.xlsx.gz":
          type: file
          description: "XLSX summary file of the metabolism"
  - versions:
      - versions.yml:
          type: file
          description: "File containing software versions"
          pattern: "versions.yml"
authors:
  - "@Ales-ibt"
  - "@Ge94"
