# yaml-language-server: $schema=https://raw.githubusercontent.com/ebi-metagenomics/nf-modules/master/subworkflows/yaml-schema.json
name: "detect_rna"
description: Extraction of specific cmsearch-identified RNA sequences from a fasta
  file using EASEL
keywords:
  - RNA
  - fasta
  - easel
  - cmsearch
  - cmscan
  - covariance models
components:
  - seqkit/split2:
    git_remote: https://github.com/nf-core/modules.git
  - cat/cat:
    git_remote: https://github.com/nf-core/modules.git
  - infernal/cmsearch
  - infernal/cmscan
  - convertcmscantocmsearch
  - cmsearchtbloutdeoverlap
  - easel/eslsfetch
  - extractcoords
input:
  - ch_fasta:
      type: file
      description: |
        The input channel containing the fasta files
        Structure: [ val(meta), path(fasta) ]
      pattern: "*.{fasta, fasta.gz, fa, fa.gz}"
  - rfam:
      type: directory
      description: |
        The folder containing Rfam database for use with cmsearch/cmscan
        Structure: path(cm)
  - claninfo:
      type: file
      description: |
        The input file containing the claninfo to use for cmsearchtbloutdeoverlap
        Structure: path(claninfo)
      pattern: "*.claninfo"
  - mode:
      type: value
      description: choose cmsearch or cmscan method to use
  - separate_subunits:
      type: boolean
      description: Specify true to separate hits into the different RNA subunits
  - chunk_flag:
      type: boolean
      description: |
        Specify true to use seqkit/split2 to chunk contigs into sequences of specific length e.g. 50M. 
        IMPORTANT NOTE, YOU HAVE TO SPECIFY CHUNK LENGTH USING `ext.args`, e.g. `--by-length 50M`.
        See nextflow.config for unit test for a full example
output:
  - versions:
      type: file
      description: |
        File containing software versions
        Structure: [ path(versions.yml) ]
      pattern: "versions.yml"
  - cmsearch_deoverlap_out:
      description: ""
  - easel_out:
      description: ""
authors:
  - "@Kate_Sakharova"
