# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "bgcsmapper"
description: Integrates BGC predictions from (optional) GECCO / antiSMASH / SanntiS outputs into a single GFF3 file
keywords:
  - sanntis
  - gecco
  - antismash
  - bgc
  - gff
tools:
  - "bgcsmapper":
      description: "Integrates BGC predictions from (optional) GECCO / antiSMASH / SanntiS outputs into a single GFF3 file"
      homepage: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      documentation: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      tool_dev_url: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      licence:
        - "Apache-2.0"
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - gff:
        type: file
        description: GFF associated to the gbc prediction tools input files
        pattern: "*.{gff,gff.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1975"
    - sanntis:
        type: file
        description: Optional GFF output generated by Sanntis tool
        pattern: "*.{gff,gff.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1975"
    - gecco:
        type: file
        description: Optional GFF output generated by Gecco tool
        pattern: "*.{gff,gff.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1975"
    - antismash:
        type: file
        description: Optional GFF output generated by AntiSMASH tool
        pattern: "*.{gff,gff.gz}"
        ontologies:
          - edam: "http://edamontology.org/format_1975"
output:
  gff:
    - - meta:
          type: map
          description: Groovy Map containing sample information
            e.g. `[id:'sample1' ]`
      - "*_bgcs.gff":
          type: file
          description: GFF file containing the integrated annotation of BGCs
          pattern: "*.gff"
  versions_python:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version | sed 's/Python //g':
          type: eval
          description: Command used to obtain the tool version

topics:
  versions:
    - - ${task.process}:
          type: string
          description: The name of the process
      - python:
          type: string
          description: The name of the tool
      - python --version | sed 's/Python //g':
          type: eval
          description: Command used to obtain the tool version

authors:
  - "@Ales-ibt"
maintainers:
  - "@Ales-ibt"
