name: "combinedgenecaller_merge"
description: |
  MGnify merging script for combined gene caller.
  The merged output contains all the gene predictions from Pyrodigal, along with genes predicted by FragGeneScanRS
  that do not overlap with any Pyrodigal gene.
  If mask file is provided, it masks (removes) genes that overlap with regions from a masking file.
keywords:
  - "gene finding"
  - "prokaryotes"
  - "microbial"

tools:
  - "combinedgenecaller":
      description: "This script merges the gene prediction with Pyrodigal and FragGeneScanRS"
      homepage: "https://www.ebi.ac.uk/metagenomics"
      documentation: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      tool_dev_url: "https://github.com/EBI-Metagenomics/combined-gene-caller"
      doi: "10.1093/nar/gkac1080"
      licence: ["Apache License 2.0"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. [ id:'test', single_end:false ]
    - pyrodigal_gff:
        type: file
        description: gene annotations in GFF format produced by Pyrodigal
        pattern: "*.gff"
    - pyrodigal_ffn:
        type: file
        description: nucleotide sequences of genes predicted by Pyrodigal
        pattern: "*.{ffn,fna}"
    - pyrodigal_faa:
        type: file
        description: protein translations of genes predicted by Pyrodigal
        pattern: "*.faa"
    - fgs_gff:
        type: file
        description: gene annotations in GFF format produced by FragGeneScanRS
        pattern: "*.gff"
    - fgs_ffn:
        type: file
        description: nucleotide sequences of genes predicted by FragGeneScanRS
        pattern: "*.{ffn,fna}"
    - fgs_faa:
        type: file
        description: protein translations of genes predicted by FragGeneScanRS
        pattern: "*.faa"
    - mask:
        type: file
        description: sequence mask file (tblout files generated by Infernal cmscan or cmsearch)
        pattern: "*.*"
output:
  - faa:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.faa.gz":
          type: file
          description: merged protein translations file
          pattern: "*.faa"
  - ffn:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.ffn.gz":
          type: file
          description: merged nucleotide sequences file
          pattern: "*.{ffn,fna}"
  - gff:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.gff.gz":
          type: file
          description: merged gene annotations in GFF format
          pattern: "*.gff"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@mberacochea"

maintainers:
  - "@mberacochea"
