# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "dbcan"
description: CAZyme annotation of proteins
keywords:
  - substrate prediction
  - annotation
  - cazyme
tools:
  - "dbcan":
      description: "Standalone version of dbCAN annotation tool for automated CAZyme
        annotation"
      homepage: "https://dbcan.readthedocs.io/en/latest/"
      documentation: "https://dbcan.readthedocs.io/en/latest/"
      tool_dev_url: "https://github.com/linnabrown/run_dbcan"
      doi: "10.1093/nar/gkad328"
      licence: ["GPL v3-or-later"]
      identifier: biotools:dbcan
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        type: file
        description: A FASTA file containing query sequences, they can be proteins of
          contigs
        pattern: "*.{fasta,faa,fa,fna}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - gff:
        type: file
        description: GFF file containing protein annotation information for the fasta
          file, only used then clusters are specified
        pattern: "*.gff"
  - - dbcan_db:
        type: directory
        description: dbCAN database
        pattern: "dbcan_db"
    - db_version:
        type: string
        description: The version of the dbCAN database
  - - mode:
        type: string
        enum:
          - prok
          - protein
          - meta
        description: Type of sequence input. protein=proteome; prok=prokaryote; meta=metagenome
output:
  - overview_txt:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_overview.tsv.gz:
          type: file
          description: "Summarizes CAZyme predictions across tools, including SignalP results."
          pattern: "results/*_overview.tsv.gz"
  - dbsub_output_tsv:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_dbcansub_hmm_results.tsv.gz:
          type: file
          description: "Output from the dbCAN_sub run."
          pattern: "results/*_dbcan_hmm_results.tsv.gz"
  - dbhmm_output_tsv:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_dbcan_hmm_results.tsv.gz:
          type: file
          description: "Output from the dbCAN_hmm run."
          pattern: "results/*_dbcan_hmm_results.tsv.gz"
  - diamond_output:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_diamond.out.gz:
          type: file
          description: "Results from the Diamond BLAST."
          pattern: "results/*_diamond.out.gz"
  - uniinput_faa:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_uniinput.faa.gz:
          type: file
          description: "The unified input file for subsequent tools, created by Prodigal if a nucleotide sequence is used."
          pattern: "results/*_uniinput.faa.gz"
  - cgc_gff:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_cgc.gff.gz:
          type: file
          description: "GFF input file for CGCFinder."
          pattern: "results/*_cgc.gff.gz"
  - cgc_standard_tsv:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_cgc_standard_out.tsv.gz:
          type: file
          description: "Simplified version of cgc.out, containing columns like CGC_id, Type, Contig_id, Gene_id, Start, End, Strand, and Annotation."
          pattern: "results/*_cgc_standard_out.tsv.gz"
  - substrate_prediction_tsv:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/${prefix}_substrate_prediction.tsv.gz:
          type: file
          description: "Summary of substrate prediction results for CGCs in TSV format from two approaches (dbCAN-PUL blast search and dbCAN-sub majority voting)"
          pattern: "results/*_substrate_prediction.tsv.gz"
  - synteny_pdfs:
      - meta:
          type: map
          description: "Groovy Map containing sample information"
      - results/synteny_pdf/*-syntenic.pdf.gz:
          type: file
          description: "Syntenic block alignment plots between all CGCs and PULs"
          pattern: "results/synteny_pdf/*-syntenic.pdf.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@jmattock5"
  - "@mberacochea"
  - "@tgurbich"
