name: "assembly_decontamination"

description: |
  MGnify Production assembly decontamination subworkflow.
  Performs sequential decontamination of assembled contigs against the human genome, PhiX and a genome
  specified by the user (usually the sample host). It designed to remove any contigs that come from any
  of those references.

keywords:
  - assembly
  - decontamination
  - contamination
  - contigs
  - metagenomics
  - phix
  - human
  - host

components:
  - decontaminate_contigs

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information and decontamination parameters.
        Expected keys:
        - phix_reference: Filename of PhiX reference genome (optional, null to skip)
        - human_reference: Filename of human reference genome (optional, null to skip)
        - contaminant_reference: Filename of custom contaminant reference (optional, null to skip)
  - assembly:
      type: file
      description: Assembly FASTA file containing contigs to be decontaminated
      pattern: "*.{fasta,fa,fna}"

output:
  - meta:
      type: map
      description: Groovy Map containing sample information
  - cleaned_contigs:
      type: file
      description: Decontaminated assembly FASTA file
      pattern: "*.{fasta,fa,fna}"
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"

authors:
  - "@jmattock5"
  - "@ochkalova"
  - "@Ge94"

maintainers:
  - "@mberacochea"
  - "@jmattock5"
  - "@ochkalova"
