# yaml-language-server: $schema=https://raw.githubusercontent.com/ebi-metagenomics/modules/master/subworkflows/yaml-schema.json
name: assembly_decontamination
description: blasts assembly against host reference genome, removes contaminant hits
keywords:
  - blast
  - seqkit
  - quality control
  - decontamination
components:
  - blast/blastn
  - seqkit/grep
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - assembly:
      type: file
      description: |
        assembly to check for contamination
      pattern: "*.{fasta,fa,fna,fasta.gz,fa.gz,fna.gz}"
  - meta2:
      type: map
      description: |
        Groovy Map containing reference information
        e.g. [ reference_genome:'chicken.fna' ]
  - ch_blast_ref:
      type: map
      description: |
        Channel containing path the collected blast database files for a specific host, eg. blast_dbs/chicken.fna
      pattern: "*"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - cleaned_contigs:
      type: file
      description: |
        the decontaminated assembly
      pattern: "*.{fasta.gz,fa.gz,fna.gz}"
  - versions:
      type: file
      description: |
        File containing software versions
      pattern: "versions.yml"
authors:
  - "@jmattock5"
