# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: "librarystrategycheck"
description: Uses base-conservation vectors to assess whether a run is AMPLICON or not
keywords:
  - fastq
  - reads
  - qc
tools:
  - "librarystrategycheck":
      description:
        "Uses base-conservation vectors to assess whether a run is AMPLICON or not, uses mgnify-pipelines-toolkit
        as conda environment"
      homepage: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      documentation: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      tool_dev_url: "https://github.com/EBI-Metagenomics/mgnify-pipelines-toolkit"
      licence: ["Apache-2.0"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - bcv:
        type: file
        description: Merged or single-end FASTQ file
        pattern: "*.fastq.gz"

output:
  - library_check_out:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - check_out:
          type: string
          description: Optional env variable containing string "AMPLICON", empty string otherwise
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@chrisata"
maintainers:
  - "@chrisata"
