name: "mapseq"
description: Perform taxonomic classification of rRNA reads using reference
  databases
keywords:
  - taxonomy
  - reads
  - otu
  - rRNA
tools:
  - "mapseq":
      description: |
        "Open source metagenomic 16S/18S read classifier enabling comparative metagenomics."
      documentation: https://github.com/jfmrod/MAPseq
      doi: "10.1093/bioinformatics/btx517"
      licence: ["dual-licensed under GPL v3+ or BSD 2-clause"]
      identifier: ""

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - subunit_reads:
        type: file
        description: FASTA file containing rRNA gene reads
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
  - - db_fasta:
        type: file
        description: Reference database FASTA file
        pattern: "*.{fa,fasta}"
        ontologies:
          - edam: http://edamontology.org/format_1929 # FASTA
    - db_tax:
        type: file
        description: Reference database OTU classifications file
        pattern: "*.txt"
        ontologies:
          - edam: http://edamontology.org/format_2330 # Text file
    - db_mscluster:
        type: file
        description: Reference database OTU pre-clustering file
        pattern: "*.txt"
        ontologies:
          - edam: http://edamontology.org/format_2330 # Text file
output:
  mseq:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. [ id:'test', single_end:false ]
      - "*.mseq":
          type: file
          description: Read classification output file
          pattern: "*.mseq"
          ontologies: []
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: "http://edamontology.org/format_3750" # YAML

authors:
  - "@chrisata"
maintainers:
  - "@chrisata"
