name: "interproscan"
description: Produces protein annotations and predictions from a FASTA file
keywords:
  - annotation
  - fasta
  - interproscan
tools:
  - "interproscan":
      description: "InterPro integrates together predictive information about proteins
        function from a number of partner resources"
      homepage: "https://www.ebi.ac.uk/interpro/search/sequence/"
      documentation: "https://interproscan-docs.readthedocs.io"
      tool_dev_url: "https://github.com/ebi-pf-team/interproscan"
      doi: "10.1093/bioinformatics/btu031"
      licence: ["GPL v3"]
      identifier: biotools:interproscan_ebi

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - fasta:
        type: file
        description: Input fasta file containing query sequences
        pattern: "*.{fa,fasta}"
  - - interproscan_db:
        type: directory
        description: Directory containing interproscan database
    - db_version:
        type: string
        description: Version of the interproscan database for the versions.yml
output:
  - tsv:
      - meta:
          type: file
          description: Tab separated file containing with detailed hits
      - "*.tsv.gz":
          type: file
          description: Tab separated file containing with detailed hits
          pattern: "*.tsv.gz"
  - xml:
      - meta:
          type: file
          description: XML file containing with detailed hits
      - "*.xml.gz":
          type: file
          description: XML file containing with detailed hits
          pattern: "*.xml.gz"
  - gff3:
      - meta:
          type: file
          description: GFF3 file containing with detailed hits
      - "*.gff3.gz":
          type: file
          description: GFF3 file containing with detailed hits
          pattern: "*.gff3.gz"
  - json:
      - meta:
          type: file
          description: JSON file containing with detailed hits
      - "*.json.gz":
          type: file
          description: JSON file containing with detailed hits
          pattern: "*.json.gz"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@mberacochea"
  - "@vagkaratzas"
