name: Build and Deploy Documentation

on:
  push:
    branches: [main]
    paths:
      - "docs/**"
      - "modules/**/meta.yml"
      - "subworkflows/**/meta.yml"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [main]
    paths:
      - "docs/**"
      - "modules/**/meta.yml"
      - "subworkflows/**/meta.yml"
      - ".github/workflows/docs.yml"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "latest"

      - name: Set up Python
        run: uv python install

      - name: Install dependencies
        working-directory: docs
        run: uv sync

      - name: Generate documentation
        working-directory: docs
        run: uv run python generate_docs.py --modules-repo .. --output-dir .

      - name: Build with MkDocs
        working-directory: docs
        run: uv run mkdocs build

      - name: Setup Pages
        if: github.ref == 'refs/heads/main'
        uses: actions/configure-pages@v5

      - name: Upload artifact
        if: github.ref == 'refs/heads/main'
        uses: actions/upload-pages-artifact@v3
        with:
          path: docs/site

  deploy:
    if: github.ref == 'refs/heads/main'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
