name: Run pytest
on:
  pull_request:
    branches: [main]
    paths:
      - "**.py"
  push:
    branches: [main]
    paths:
      - "**.py"

jobs:
  pytest:
    runs-on: ubuntu-latest
    name: pytest

    steps:
      - uses: actions/checkout@v5.0.0

      - name: Install uv
        uses: astral-sh/setup-uv@v7.1.2

      - name: Install Task
        uses: go-task/setup-task@v1

      - name: Run pytest via Task
        run: task modules-pytest
